### ISSUE TITLE
Don't use the `Exception` base class

### ISSUE THREAD

**Issue by shenanigansd** [vipyrsec/dragonfly-loader#10]
https://github.com/vipyrsec/dragonfly-loader/blob/909810f18dfb9d0218c73b7e3fb229127222d102/src/loader/settings.py#L33-L43
This should implement a custom exception class.
Or even better, use `pydantic-settings`.

**Comment by AbooMinister25** [comment]
This should be resolved now, Robin's PR (#16) switches to pydantic-settings.
